value:
  type: "product"
  data:
    -
      id: "5e98e0eb25d98575bc04bad1"
      name: "TESTING (DO NOT BUY)- Baby One Suit"
      description: "<p><strong>(TEST - DO NOT BUY)</strong></p> <p>...</p>"
      price: 10
      package:
        weight: 1
        height: 1
        length: 1
        width: 1
        content: null
      integrations:
        -
          id: "lazada_sg"
          name: "lazada-sg"
          channel: "Ov2LazadaSG"
          channel_title: "Lazada [SG]"
          product:
            remote_product_id: "650628600"
      images:
        - "https://sg-live.slatic.net/p/ea02ecadf6a0887347a00a00afbc5a4c.jpg"
      variants: 1
      created_at: "2020-04-16T22:49:15+00:00"
      updated_at: "2020-04-16T22:49:15+00:00"
    -
      id: "5e98e0e225d98532b50d6740"
      name: "Cherry Midi Dress (TESTING - DO NOT BUY)"
      description: "<p><strong>(TESTING - DO NOT BUY)</strong></p> <p>A stunner silhouette, ...</p>"
      price: 50
      package:
        weight: 1
        height: 1
        length: 1
        width: 1
        content: "..."
      integrations:
        -
          id: "lazada_sg"
          name: "lazada-sg"
          channel: "Ov2LazadaSG"
          channel_title: "Lazada [SG]"
          product:
            remote_product_id: "628860213"
      images:
        - "https://sg-live.slatic.net/p/30324db42e46aebd60ed9cef59880078.jpg"
        - "https://sg-live.slatic.net/p/16e6c249cb9b937749c3e48b6a4cf992.jpg"
      variants: 4
      created_at: "2020-04-16T22:49:06+00:00"
      updated_at: "2020-04-17T21:14:12+00:00"

  pagination:
    offset: 0
    limit: 10
    total: 2