value:
  type: "product"
  data:
    id: 5d48c54125d9852031005fc3
    name: IPod Nano - 8GB
    description: "It's the small iPod with one very big idea: Video..."
    price: 199.0
    variants: 1
    images:
      - https://cf.lazada.sg/file/dfd9210dc1f3ec1b7432d5ac0cf000
      - https://cf.lazada.sg/file/dfd9210dc1f3ec1b7432d5ac0cf001

    integrations:
      - id: shop_01
        name: Shop-01
        channel: LazadaSG
        product:
          remote_product_id: '289247362'
          category_id: '10001946'
          properties:
            - id: category_id
              label: Category
              required: true
              input_type: single_select_with_remote_options
              options:
                - id: 7540
                  value: Smart Devices > Smart Trackers
              options_service_path: /integrations/lazada_sg/categories
              value: 7540
            - id: warranty_type
              label: Warranty Type
              required: false
              input_type: single_select
              options:
                - International Manufacturer Warranty
                - International Seller Warranty
                - Local (Singapore) manufacturer warranty
                - Local seller warranty
                - No Warranty
                - Non-local warranty
              value: International Manufacturer Warranty
            - id: warranty
              name: warranty
              label: Warranty Period
              required: false
              input_type: single_select
              options:
                - 1 Month
                - 1 Year
                - 10 Months
                - 10 Years
                - Life Time Warranty
              value: 1 Month
            - id: brand
              name: brand
              label: Brand
              required: true
              input_type: single_select
              value: No Brand
            - id: delivery_option_economy
              name: delivery_option_economy
              label: Delivery Option Economy
              required: false
              input_type: single_select
              options:
                - 'No'
                - 'Yes'
              value: Yes
            - id: short_description
              name: short_description
              label: Highlights
              required: true
              input_type: rich_text
              value: It's the small iPod with one very big idea