value:
  type: "product"
  data:
    id: "5e98e0eb25d98575bc04bad1"
    name: "TESTING (DO NOT BUY)- Baby One Suit"
    description: "<p><strong>(TEST - DO NOT BUY)</strong></p> <p>...</p>"
    price: 10
    package:
      weight: 1
      height: 1
      length: 1
      width: 1
      content: null
    integrations:
      -
        id: "lazada_sg"
        name: "lazada-sg"
        channel: "Ov2LazadaSG"
        channel_title: "Lazada [SG]"
        product:
          remote_product_id: "650628600"
          properties:
            -
              id: "category_id"
              label: "Category"
              required: true
              read_only: true
              input_type: "single_select_with_remote_options"
              options:
                -
                  id: "8911"
                  name: "Mother & Baby > Baby Gear > Playards & Playpens"
              options_service_path: "/integrations/lazada_sg/categories"
              value: "8911"
            -
              id: "video"
              label: "Video URL"
              required: false
              read_only: false
              input_type: "text"
              options: []
              value: null
            -
              id: "brand"
              label: "Brand"
              required: true
              read_only: false
              input_type: "single_select_with_remote_options"
              options:
                -
                  id: "23888"
                  name: "3M"
              value: "3M"
              options_service_path: "/integrations/lazada_sg/brands"
            -
              id: "model"
              label: "Model"
              required: false
              read_only: false
              input_type: "text"
              options: []
              value: null
            -
              id: "Folded_dimension"
              label: "Folded dimension"
              required: false
              read_only: false
              input_type: "text"
              options: []
              value: null
            -
              id: "Maxmium_child_weight"
              label: "Maximum child weight"
              required: false
              read_only: false
              input_type: "numeric"
              options: []
              value: null
            -
              id: "No_of_pieces"
              label: "No of Pieces"
              required: false
              read_only: false
              input_type: "numeric"
              options: []
              value: null
            -
              id: "Open_dimension"
              label: "Open Dimension"
              required: false
              read_only: false
              input_type: "text"
              options: []
              value: null
            -
              id: "warranty_type"
              label: "Warranty Type"
              required: false
              read_only: false
              input_type: "single_select"
              options:
                - "International Manufacturer Warranty"
                - "International Seller Warranty"
                - "Local (Singapore) manufacturer warranty"
                - "Local seller warranty"
                - "No Warranty"
                - "Non-local warranty"
              value: "International Manufacturer Warranty"
            -
              id: "wheels"
              label: "Wheels"
              required: false
              read_only: false
              input_type: "single_select"
              options:
                - "No"
                - "Yes"
              value: "No"
            -
              id: "warranty"
              label: "Warranty Period"
              required: false
              read_only: false
              input_type: "single_select"
              options:
                - "1 Month"
                - "1 Year"
                - "10 Months"
                - "10 Years"
                - "11 Months"
                - "12 Years"
                - "15 Years"
                - "18 Months"
                - "2 Months"
                - "2 Years"
                - "25 Years"
                - "3 Months"
                - "3 Years"
                - "30 Years"
                - "4 Months"
                - "4 Years"
                - "5 Months"
                - "5 Years"
                - "6 Months"
                - "6 Years"
                - "7 Months"
                - "7 Years"
                - "8 Months"
                - "8 Years"
                - "9 Months"
                - "Life Time Warranty"
              value: "1 Month"
            -
              id: "product_warranty"
              label: "Warranty Policy"
              required: false
              read_only: false
              input_type: "text"
              options: []
              value: null
            -
              id: "short_description"
              label: "Highlights"
              required: true
              read_only: false
              input_type: "rich_text"
              options: []
              value: "<p>TEST - DO NOT BUY</p>"
            -
              id: "delivery_option_express"
              label: "Delivery Option Express"
              required: false
              read_only: false
              input_type: "single_select"
              options:
                - "No"
                - "Yes"
              value: null
            -
              id: "delivery_option_economy"
              label: "Delivery Option Economy"
              required: false
              read_only: false
              input_type: "single_select"
              options:
                - "No"
                - "Yes"
              value: null
            -
              id: "Hazmat"
              label: "Dangerous Goods"
              required: false
              read_only: false
              input_type: "multi_select"
              options:
                - "Battery"
                - "Flammable"
                - "Liquid"
                - "None"
              value: null
    images:
      - "https://sg-live.slatic.net/p/ea02ecadf6a0887347a00a00afbc5a4c.jpg"
    variants: 1
    created_at: "2020-04-16T22:49:15+00:00"
    updated_at: "2020-04-16T22:49:15+00:00"
