description: Success
content:
  application/json:
    schema:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ResponseResourceType'
        data:
          $ref: '#/components/schemas/Product'

    examples:
      Ex1:
        $ref: '#/components/examples/product_item_response'