description: Success
content:
  application/json:
    schema:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ResponseResourceType'
        data:
          description: Product representations in CenitIO eCommerce
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/Product"
              - type: object
                properties:
                  integrations:
                    type: array
                    readOnly: true
                    items:
                      $ref: "#/components/schemas/ProductIntegration"

        pagination:
            $ref: '#/components/schemas/Pagination'