type: object
required: [product_ids]
properties:
  product_ids:
    description: Identifiers of the products to be processed.
    type: array
    minItems: 1
    maxItems: 100
    items:
      type: string