allOf:
  - $ref: "#/components/schemas/IntegrationMin"
  - type: object
    properties:
      product:
        description: Details of the remote product of the integration.
        type: object
        properties:
          remote_product_id:
            description: Identifier of the remote product of the integration.
            type: string
          properties:
            type: array
            items:
              $ref: "#/components/schemas/ProductProperty"
          stock_item:
            description: Stock items
            $ref: "#/components/schemas/StockItemMin"