type: object
properties:
  id:
    description: Property identifier
    type: string
  label:
    description: Property label
    type: string
  required:
    description: Property name
    type: boolean
  input_type:
    description: Property input component type
    type: string
  value:
    description: Value of the property in the product instance
    type: string