type: object
properties:
  id:
    description: Integration identifier
    type: string
  name:
    description: Integration name
    type: string
  channel:
    description: Integration channel identifier
    type: string

  product:
    description: Details of the remote product of the integration.
    type: object
    properties:
      remote_product_id:
        description: Identifier of the remote product of the integration.
        type: string
      properties:
        type: array
        items:
          $ref: "#/components/schemas/ProductProperty"