description: Package dimensions and content
type: "object"
properties:
  weight:
    description: Package weight in kg
    type: number
    minimum: 0
  height:
    description: Package height in cm
    type: integer
    minimum: 0
  length:
    description: Package length in cm
    type: integer
    minimum: 0
  width:
    description: Package width in cm
    type: integer
    minimum: 0
  content:
    description: What's in the package?
    type: string