type: object
properties:
  id:
    description: Property identifier
    type: string
  label:
    description: Property label
    type: string
    readOnly: true
  required:
    description: Define if the property is mandatory
    type: boolean
    readOnly: true
  read_only:
    description: Define if the property is read only
    type: boolean
    readOnly: true
  input_type:
    description: Property input component type
    type: string
    readOnly: true
  options:
    description: Options for inputs of selection types
    type: array
    readOnly: true
    items:
      type: string
  options_service_path:
    description: Relative path of the web service to retrieve the options in the selection field.
    type: string
    readOnly: true
  value:
    description: Value of the property in the product instance
    type: string