description: Product representation in OMNA
type: object
properties:
  id:
    description: Product identifier
    type: string
    readOnly: true
  name:
    description: Product name
    type: string
  description:
    description: Product description
    type: string
  price:
    description: Product price
    type: number
    minimum: 0
  variants:
    description: Number of the product variants
    type: number
    readOnly: true
    minimum: 0
  package:
    allOf:
      - $ref: "#/components/schemas/ProductPackage"
  images:
    description: Product images
    type: array
    readOnly: true
    items:
      type: string
  integrations:
    type: array
    readOnly: true
    items:
      $ref: "#/components/schemas/ProductIntegration"