description: Product representation in OMNA
type: object
properties:
  id:
    description: Product identifier
    type: string
    readOnly: true
  name:
    description: Product name
    type: string
  description:
    description: Product description
    type: string
  price:
    description: Product price
    type: number
    minimum: 0
  quantity:
    description: Quantity of items available from the product
    type: integer
    readOnly: true
  variants:
    description: Number of the product variants
    type: integer
    readOnly: true
  package:
    allOf:
      - $ref: "#/components/schemas/ProductPackage"
  images:
    description: Product images
    type: array
    readOnly: true
    items:
      type: string
  created_at:
    $ref: "#/components/schemas/CreatedAt"
  updated_at:
    $ref: "#/components/schemas/UpdatedAt"