allOf:
  - $ref: "#/components/schemas/Product"
  - type: object
    properties:
      package:
        type: "object"
        required: [overwrite]
        properties:
          overwrite:
            description: Do overwrite package information in all variants
            type: boolean