type: object
properties:
  id:
    description: Integration identifier
    type: string
  name:
    description: Integration name
    type: string
  channel:
    description: Integration channel identifier
    type: string

  product:
    description: Details of the remote product of the integration
    type: object
    properties:
      id:
        description: Identifier of the remote product of the integration
        type: string
      name:
        description: Name of the remote product of the integration
        type: string
      category_id:
        description: Category identifier of the remote product of the integration
        type: string
      properties:
        type: array
        items:
          $ref: "#/components/schemas/ProductProperty"



      
    
  
