type: object
properties:
  id:
    description: Property identifier
    type: string
  label:
    description: Property label
    type: string
    readOnly: true
  required:
    description: Define if the property is mandatory
    type: boolean
    readOnly: true
  input_type:
    description: Property input component type
    type: string
    readOnly: true
  options:
    description: Options for inputs of selection types
    type: array
    readOnly: true
    items:
      type: string
  value:
    description: Value of the property in the product instance
    type: string