openapi: 3.0.0
info:
  version: v1
  title: OMNA Commerce API
  termsOfService: 'https://example.com/terms/'
  contact:
    email: support@cenit.io
    url: 'https://cenitio.slack.com/messages/support'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'omna_logo.png'
  description: >
    # Introduction

    * The OMNA Commerce API is built over REST services on HTTPS.

    * It has predictable resource URLs.

    * It returns HTTP response codes to indicate errors.

    * It also accepts and returns JSON in the HTTP body.

    * You can use your favorite HTTP/REST library for your programming language to use OMNA Commerce API,

    # Authentication

    TODO: ....

tags:
  - name: Stores
    description: Operations about stores
  - name: Orders
    description: Operations about orders
  - name: Flows
    description: Operations about flows
  - name: Webhooks
    description: Operations about webhooks
  - name: Tasks
    description: Operations about tasks


servers:
  - url: 'https://cenit.io/app/ecapi'
