openapi: 3.0.0
info:
  version: v1
  title: eCapi
  termsOfService: 'https://example.com/terms/'
  contact:
    email: support@cenit.io
    url: 'https://cenitio.slack.com/messages/support'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://cenit.io/assets/cenit-logo-c4e099552f7dc77c1870b7c77600380177da8b01c0a4a70dbf608b73e61da3ce.png'
  description: >
    # Introduction

    * The eCommerce's API is built over REST services on HTTPS.

    * It has predictable resource URLs.

    * It returns HTTP response codes to indicate errors.

    * It also accepts and returns JSON in the HTTP body.

    * You can use your favorite HTTP/REST library for your programming language to use eCommerce's API,

    # Authentication

    TODO: ...

tags:
  - name: Store
    description: Operations about store
  - name: Order
    description: Operations about orders
  - name: Tasks
    description: Operations about tasks

servers:
  - url: 'https://cenit.io/app/ecapi'
