openapi: 3.0.0
info:
  version: v1
  title: OMNA COMMERCE API
  termsOfService: 'https://cenit.io/terms'
  contact:
    email: hello@omna.io
    url: 'https://cenitio.slack.com/messages/support'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: omna_logo.png
  description: >
    # Introduction

    * The OMNA COMMERCE API is built over REST services on HTTPS.

    * It has predictable resource URLs.

    * It returns HTTP response codes to indicate errors.

    * It also accepts and returns JSON in the HTTP body.

    * You can use your favorite HTTP/REST library for your programming language
    to use OMNA COMMERCE API.

tags:
  - name: Integrations
    description: Operations about integrations
  - name: Orders
    description: Operations about orders
  - name: Flows
    description: Operations about flows
  - name: Webhooks
    description: Operations about webhooks
  - name: Tasks
    description: Operations about tasks
  - name: Users
    description: Operations about users and tenants

servers:
  - url: 'https://cenit.io/app/ecapi-v1'

security:
  - Token: []
    Timestamp: []
    HMac: []