description: Product properties that will be updated
required: true
content:
  application/json:
    schema:
      required: [data]
      properties:
        data:
          allOf:
            - $ref: "#/components/schemas/Product"
            - type: object
              properties:
                package:
                  type: "object"
                  required: [overwrite]
                  properties:
                    overwrite:
                      description: Do overwrite package information in all variants
                      type: boolean

    examples:
      Ex1:
        $ref: '#/components/examples/product_update_request_1'
      Ex2:
        $ref: '#/components/examples/product_update_request_2'