description: |
  Identifiers of the products and integrations that will be linked.
required: true
content:
  application/json:
    schema:
      required: [data]
      properties:
        data:
          type: object
          allOf:
            - $ref: "#/components/schemas/ProductIDs"
            - $ref: "#/components/schemas/IntegrationIDs"
            - $ref: "#/components/schemas/ProductLinkVariants"