description: Product properties that will be updated
required: true
content:
  application/json:
    schema:
      required: [data]
      properties:
        data:
          allOf:
            - $ref: "#/components/schemas/Product"
            - type: object
              properties:
                package:
                  type: "object"
                  required: [overwrite]
                  properties:
                    overwrite:
                      description: Do overwrite package information in all variants
                      type: boolean
                product_ids:
                  description: Identifiers of the products to be updated
                  type: array
                  minItems: 1
                  maxItems: 100
                  items:
                    type: string