description: Product properties that will be updated
required: true
content:
  application/json:
    schema:
      required: [data]
      properties:
        data:
          allOf:
            - $ref: "#/components/schemas/ProductUpdate"