description: |
  Identifiers of the products and integrations that will be linked.
required: true
content:
  application/json:
    schema:
      required: [data]
      properties:
        data:
          type: object
          properties:
            product_ids:
              description: Identifiers of the products to be linked.
              type: array
              items:
                type: string
            integration_ids:
              description: Identifiers of the integrations with which you want to link the product.
              type: array
              items:
                type: string
            link_with_its_variants:
              description: |
                Establishes how the product integrations should be linked or not with its variants.
                * **NONE**: Do not link with any of its variants.
                * **SELECTED**: Link only selected product integrations with all its variants.
                * **NEW**: Link only new product integrations with all its variants.
                * **ALL**: Link all product integrations with all its variants.
              type: string
              enum:
                - NONE
                - SELECTED
                - NEW
                - ALL
          required: [product_ids, integration_ids]

    examples:
      Ex1:
        $ref: '#/components/examples/product_link_request'