description: Product that will be added to the system
required: true
content:
  application/json:
    schema:
      required: [data]
      properties:
        data:
          allOf:
            - $ref: "#/components/schemas/Product"
            - required: [name, description, price]
