description: |
  Integrations IDs and data to set whether the product should be removed from the remote integration source.
required: true
content:
  application/json:
    schema:
      required: [data]
      properties:
        data:
          type: object
          properties:
            integration_ids:
              description: Identifiers of the integrations with which you want to unlink the product.
              type: array
              items:
                type: string
            delete_from_integration:
              description: |
                Set whether the product should be removed from the remote integration source.
              type: boolean
              default: false
          required: [integration_ids]