description: |
  Integrations IDs and data to sets whether the product should be removed from OMNA and/or the remote integration source.
required: true
content:
  application/json:
    schema:
      required: [data]
      properties:
        data:
          type: object
          properties:
            integration_ids:
              description: Identifiers of the integrations where you want to unpublish the product.
              type: array
              items:
                type: string
            delete_from_integration:
              description: |
                Sets whether the product should be removed from the remote integration source.
              type: boolean
              default: false
          required: [integration_ids]

    examples:
      Ex1:
        $ref: '#/components/examples/product_unpublish_request'