parameters:
  - $ref: '#/components/parameters/path_product_id'

get:
  tags:
    - Products
  operationId: get_product
  summary: Retrieve a Product
  description: |
    Retrieves a single product by its identifier.
  responses:
    '200':
      $ref: '#/components/responses/product_item'
    '404':
      $ref: '#/components/responses/product_not_found'

post:
  tags:
    - Products
  operationId: update_product
  summary: Update a Product
  description: |
    Update the common properties of a product.
  requestBody:
    $ref: '#/components/requestBodies/product_update'
  responses:
    '200':
      $ref: '#/components/responses/product_item'
    '404':
      $ref: '#/components/responses/product_not_found'

delete:
  tags:
    - Products
  operationId: delete_product
  summary: Delete a Product
  description: |
    Delete a unlinked product.

    > The product will be permanently removed if and only if it has no associated integrations.
  responses:
    '200':
      $ref: '#/components/responses/success'
    '404':
      $ref: '#/components/responses/product_not_found'
