parameters:
  - $ref: '#/components/parameters/path_product_id'

get:
  tags:
    - Products
  operationId: get_product_beta
  summary: Retrieve a Product
  description: |
    Retrieves a single product by given id.
  responses:
    '200':
      $ref: '#/components/responses/product_item'
    '404':
      $ref: '#/components/responses/product_not_found'

post:
  tags:
    - Products
  operationId: update_product_beta
  summary: Update a Product
  description: |
    Update the common properties of a product.
  requestBody:
    $ref: '#/components/requestBodies/product_update'
  responses:
    '200':
      $ref: '#/components/responses/product_item'
    '404':
      $ref: '#/components/responses/product_not_found'

put:
  tags:
    - Products
  operationId: publish_product_beta
  summary: Publish a Product
  description: |
    Publish a product in the given integrations.
  requestBody:
    $ref: '#/components/requestBodies/product_publish'
  responses:
    '200':
      $ref: '#/components/responses/task_item'
    '404':
      $ref: '#/components/responses/product_not_found'
      
delete:
  tags:
    - Products
  operationId: delete_product_beta
  summary: Unpublish a Product
  description: |
    Unpublish a product from the given integrations.

    > The product will be permanently removed if it is established that it must be removed from OMNA if it is not published in at least one integration.
  requestBody:
    $ref: '#/components/requestBodies/product_unpublish'
  responses:
    '200':
      $ref: '#/components/responses/task_item'
    '404':
      $ref: '#/components/responses/product_not_found'