parameters:
  - $ref: '#/components/parameters/path_product_id'

get:
  tags:
    - Variants
  operationId: get_variants
  summary: List all Variants
  description: |
    Retrieves a list of product variants.
  parameters:
    - $ref: '#/components/parameters/query_filter_term_for_variants'
    - $ref: '#/components/parameters/query_filter_integration'
    - $ref: '#/components/parameters/query_filter_generic_created_after'
    - $ref: '#/components/parameters/query_filter_generic_created_before'
    - $ref: '#/components/parameters/query_filter_generic_updated_after'
    - $ref: '#/components/parameters/query_filter_generic_updated_before'
    - $ref: '#/components/parameters/query_with_details'
    - $ref: '#/components/parameters/query_without_data'
    - $ref: '#/components/parameters/query_offset'
    - $ref: '#/components/parameters/query_limit'
    - $ref: '#/components/parameters/query_sort_for_variants'
  responses:
    '200':
      $ref: '#/components/responses/variant_items'

post:
  tags:
    - Variants
  operationId: create_variant
  summary: Create a Variant
  description: |
    Create a new product variant.
  requestBody:
    $ref: '#/components/requestBodies/variant_update'
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

put:
  tags:
    - Variants
  operationId: update_variants
  summary: Update multiple Variants
  description: |
    Update the common properties of multiple product variants.
  requestBody:
    $ref: '#/components/requestBodies/variant_update_bulk'
  responses:
    '200':
      $ref: '#/components/responses/variant_items'

delete:
  tags:
    - Variants
  operationId: delete_multiple_variants_beta_
  summary: Delete multiple Variants
  description: |
    It delete multiple unlinked product variants.

    > The variants will be permanently removed if and only if it has no associated integrations.
  requestBody:
    $ref: '#/components/requestBodies/variant_ids'
  responses:
    '200':
      $ref: '#/components/responses/success'
    '404':
      $ref: '#/components/responses/variant_not_found'