parameters:
 - $ref: '#/components/parameters/path_product_id'
 - $ref: '#/components/parameters/path_variant_id'

put:
  tags:
    - Variants
  operationId: link_variant
  summary: Link a Variant
  description: |
    It generates an asynchronous task to link a product variant with multiple integrations.

    > If the process is successful, tasks will be added to create or update the product variant on the remote platforms of each linked integration.
  requestBody:
    $ref: '#/components/requestBodies/variant_link'
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'
      
delete:
  tags:
    - Variants
  operationId: unlink_variant_async
  summary: Unlink a Variant
  description: |
    It generates an asynchronous task to unlink a product variant with multiple integrations.

    > If it is established that the product variant should be removed from the remote integration source, then a task is also created to achieve this goal.
  requestBody:
    $ref: '#/components/requestBodies/variant_unlink'
  responses:
    '200':
      $ref: '#/components/responses/task_item'
    '404':
      $ref: '#/components/responses/variant_not_found'