parameters:
  - $ref: '#/components/parameters/path_product_id'

delete:
  tags:
    - Variants
  operationId: delete_all_unlinked_variants_beta_
  summary: Delete unliked variants
  description: |
    Generate an asynchronous task to remove all unlinked variants of a product.
  responses:
    '200':
      $ref: '#/components/responses/task_item'
