parameters:
  - $ref: '#/components/parameters/query_filter_term_for_products'
  - $ref: '#/components/parameters/query_filter_integration'
  - $ref: '#/components/parameters/query_with_details'
  - $ref: '#/components/parameters/query_offset'
  - $ref: '#/components/parameters/query_limit'

get:
  tags:
    - Products
  operationId: get_products_beta
  summary: LIST ALL PRODUCTS
  description: |
    Retrieves a list of products.
  responses:
    '200':
      $ref: '#/components/responses/product_items'
