parameters:
  - $ref: '#/components/parameters/path_product_id'

get:
  tags:
    - Stock Items
  operationId: get_product_stock_items
  x-menu-position: 2
  summary: List a Product Stock Items
  description: |
    Returns the list of stock items of a product.
  parameters:
    - $ref: '#/components/parameters/query_filter_term_for_stock_items'
    - $ref: '#/components/parameters/query_filter_integration'
    - $ref: '#/components/parameters/query_filter_variant_id'
    - $ref: '#/components/parameters/query_filter_generic_created_after'
    - $ref: '#/components/parameters/query_filter_generic_created_before'
    - $ref: '#/components/parameters/query_filter_generic_updated_after'
    - $ref: '#/components/parameters/query_filter_generic_updated_before'
    - $ref: '#/components/parameters/query_offset'
    - $ref: '#/components/parameters/query_limit'
    - $ref: '#/components/parameters/query_sort_for_stock_items'
  responses:
    '200':
      $ref: '#/components/responses/stock_item_items'
