parameters:
  - $ref: '#/components/parameters/path_product_id'
  - $ref: '#/components/parameters/query_filter_term_for_variants'
  - $ref: '#/components/parameters/query_filter_integration'
  - $ref: '#/components/parameters/query_with_details'
  - $ref: '#/components/parameters/query_without_data'
  - $ref: '#/components/parameters/query_offset'
  - $ref: '#/components/parameters/query_limit'

get:
  tags:
    - Variants
  operationId: get_variants_beta_
  summary: List all Variants
  description: |
    Retrieves a list of variants.
  responses:
    '200':
      $ref: '#/components/responses/variant_items'
