parameters:
 - $ref: '#/components/parameters/path_product_id'
 - $ref: '#/components/parameters/path_variant_id'

get:
  tags:
    - Variants
  operationId: get_variant_beta_
  summary: Retrieve a Variant
  description: |
    Retrieves a single product variant by its identifier.
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

post:
  tags:
    - Variants
  operationId: update_variant_beta_
  summary: Update a Variant
  description: |
    Update the common properties of a variant.
  requestBody:
    $ref: '#/components/requestBodies/variant_update'
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

put:
  tags:
    - Variants
  operationId: link_variant_beta_
  summary: Link a Variant
  description: |
    Generate an async task to link a product variant with some integrations.

    > If the process is successful, tasks will be added to create or update the product variant on the remote platforms of each linked integration.
  requestBody:
    $ref: '#/components/requestBodies/variant_link'
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'
      
patch:
  tags:
    - Variants
  operationId: unlink_variant_async_beta_
  summary: Unlink a Variant
  description: |
    Generate an async task to unlink a product variant with some integrations.

    > If it is established that the product variant should be removed from the remote integration source, then a task is also created to achieve this goal.
  requestBody:
    $ref: '#/components/requestBodies/variant_unlink'
  responses:
    '200':
      $ref: '#/components/responses/task_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

delete:
  tags:
    - Variants
  operationId: delete_variant_beta_
  summary: Delete a variant
  description: |
    Delete a product variant without integrations.

    > The variant will be permanently removed if and only if it has no associated integrations.
  responses:
    '200':
      $ref: '#/components/responses/success'
    '404':
      $ref: '#/components/responses/variant_not_found'