parameters:
 - $ref: '#/components/parameters/path_product_id'
 - $ref: '#/components/parameters/path_variant_id'

get:
  tags:
    - Variants
  operationId: get_variant_beta_
  summary: Retrieve a Variant
  description: |
    Retrieves a single variant by its identifier.
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

post:
  tags:
    - Variants
  operationId: update_variant_beta_
  summary: Update a Variant
  description: |
    Update the common properties of a variant.
  requestBody:
    $ref: '#/components/requestBodies/variant_update'
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

put:
  tags:
    - Variants
  operationId: publish_variant_beta_
  summary: Publish a Variant
  description: |
    Publish a variant in the given integrations.
  requestBody:
    $ref: '#/components/requestBodies/variant_publish'
  responses:
    '200':
      $ref: '#/components/responses/product_item'
    '404':
      $ref: '#/components/responses/variant_not_found'
      
patch:
  tags:
    - Variants
  operationId: unlink_variant_async_beta_
  summary: Unlink a Variant
  description: |
    Generate an async task to unlink a product variant with some integrations.

    > If it is established that the product variant should be removed from the remote integration source, then a task is also created to achieve this goal.
  requestBody:
    $ref: '#/components/requestBodies/variant_unlink'
  responses:
    '200':
      $ref: '#/components/responses/task_item'
    '404':
      $ref: '#/components/responses/variant_not_found'