post:
  tags:
    - Products
  operationId: link_some_products_async_beta_
  summary: Link some Products
  description: |
    Generate asynchronous tasks to link some products with some integrations.

    > If the process is successful, tasks will be added to create or update the products on the remote platforms of each linked integration.
  requestBody:
    $ref: '#/components/requestBodies/product_link_bulk'
  responses:
    '200':
      $ref: '#/components/responses/task_items'
    '404':
      $ref: '#/components/responses/product_not_found'

delete:
  tags:
    - Products
  operationId: unlink_some_products_async_beta_
  summary: Unlink some Products
  description: |
    Generate asynchronous tasks to unlink some products with some integrations.

    > If it is established that the products should be removed from the remote integration source, then a task is also created to achieve this goal.
  requestBody:
    $ref: '#/components/requestBodies/product_unlink_bulk'
  responses:
    '200':
      $ref: '#/components/responses/task_items'
    '404':
      $ref: '#/components/responses/product_not_found'

