parameters:
  - $ref: '#/components/parameters/path_product_id'

put:
  tags:
    - Variants
  operationId: link_multiple_variants_async_beta_
  summary: Link multiple Variants
  description: |
    It generatea an asynchronous task to link multiple variants with multiple integrations.

    > If the process is successful, some tasks will be added to create or update the variants on the remote platforms of each linked integration.
  requestBody:
    $ref: '#/components/requestBodies/variant_link_bulk'
  responses:
    '200':
      $ref: '#/components/responses/task_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

delete:
  tags:
    - Variants
  operationId: unlink_multiple_variants_async_beta_
  summary: Unlink multiple Variants
  description: |
    It generate an asynchronous task to unlink multiple variants with multiple integrations.

    > If it is established that the variants should be removed from the remote integration source, then a task is also created to achieve this goal.
  requestBody:
    $ref: '#/components/requestBodies/variant_unlink_bulk'
  responses:
    '200':
      $ref: '#/components/responses/task_item'
    '404':
      $ref: '#/components/responses/variant_not_found'