parameters:
 - $ref: '#/components/parameters/path_product_id'
 - $ref: '#/components/parameters/path_variant_id'

get:
  tags:
    - Variants
  operationId: get_variant
  summary: Retrieve a Variant
  description: |
    Retrieves a single product variant by its identifier.
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

post:
  tags:
    - Variants
  operationId: update_variant
  summary: Update a Variant
  description: |
    Update the common properties of a variant.
  requestBody:
    $ref: '#/components/requestBodies/variant_update'
  responses:
    '200':
      $ref: '#/components/responses/variant_item'
    '404':
      $ref: '#/components/responses/variant_not_found'

delete:
  tags:
    - Variants
  operationId: delete_variant
  summary: Delete a variant
  description: |
    Delete a unlinked product variant.

    > The variant will be permanently removed if and only if it has no associated integrations.
  responses:
    '200':
      $ref: '#/components/responses/success'
    '404':
      $ref: '#/components/responses/variant_not_found'