get:
  tags:
    - Products
  operationId: get_products_beta_
  summary: List all Products
  description: |
    Retrieves a list of products.
  parameters:
    - $ref: '#/components/parameters/query_filter_term_for_products'
    - $ref: '#/components/parameters/query_filter_integration'
    - $ref: '#/components/parameters/query_filter_category_in_omna_product'
    - $ref: '#/components/parameters/query_filter_product_created_after'
    - $ref: '#/components/parameters/query_filter_product_created_before'
    - $ref: '#/components/parameters/query_filter_product_updated_after'
    - $ref: '#/components/parameters/query_filter_product_updated_before'
    - $ref: '#/components/parameters/query_with_details'
    - $ref: '#/components/parameters/query_without_data'
    - $ref: '#/components/parameters/query_offset'
    - $ref: '#/components/parameters/query_limit'
    - $ref: '#/components/parameters/query_sort_for_products'
  responses:
    '200':
      $ref: '#/components/responses/product_items'

post:
  tags:
    - Products
  operationId: create_product_beta_
  summary: Create a Product
  description: |
    Create a new product.
  requestBody:
    $ref: '#/components/requestBodies/product_create'
  responses:
    '200':
      $ref: '#/components/responses/product_item'
    '404':
      $ref: '#/components/responses/product_not_found'

put:
  tags:
    - Products
  operationId: update_products_beta_
  summary: Update multiple Product
  description: |
    Update the common properties of multiple products with the same information.
  requestBody:
    $ref: '#/components/requestBodies/product_update_bulk'
  responses:
    '200':
      $ref: '#/components/responses/product_items'

delete:
  tags:
    - Products
  operationId: delete_some_products_beta_
  summary: Delete some Product
  description: |
    Delete some products without integrations.

    > The products will be permanently removed if and only if it has no associated integrations.
  requestBody:
    $ref: '#/components/requestBodies/product_ids'
  responses:
    '200':
      $ref: '#/components/responses/success'
    '404':
      $ref: '#/components/responses/product_not_found'